name: Validate with HACS

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"  # daily run

jobs:
  hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
